### ISSUE TITLE
db.default resetting the values

### ISSUE THREAD

**Issue by lohithmust** [typicode/lowdb#277] opened 2018-06-06 10:41 UTC
@@##As in the documentation , When I am using the db.defaults after writing the data .my db.json file getting empty .sometimes it showing the data but after sometime its getting empty again.

**Comment by typicode** [comment] 2018-06-11 15:59
Hi @lohithmust,

That's strange, would you have a code example to reproduce the error?

**Comment by lohithmust** [comment] 2018-06-12 06:28
Yeah , I feel it too @typicode   below is the code . It's working fine when I comment the db.default if not my json file is getting resetted.

`const FileSync = require('lowdb/adapters/FileSync')
const adapter = new FileSync('db.json');
const db = low(adapter);

const products = [];
//this below two lines are required to write in the db.json files
//this below code should be executed for first time and afterwards you can comment it
db.defaults({ products: [], name: 'ecommerce store' })
   .write();`

**Comment by runemadsen** [comment] 2018-11-02 08:41
+1

**Comment by piuccio** [comment] 2018-12-07 02:31
Actually I think my problem is because I'm running the script in a cron task and it appears that sometimes the previous task didn't finish be the time the next one starts, so maybe it's a concurrency problem?

**Comment by userabuser** [comment] 2018-12-14 12:09
@piuccio I experienced the same issue, in my case, instead of `cron`, it was `nodemon`.

In my case this was fixed by specifying which file to watch as opposed to all in root directory. 

For anyone else experiencing a similar issue it will likely be because of something similar, e.g. `cron`, `nodemon`, other file watchers etc.

**Comment by aviaryan** [comment] 2019-03-23 13:35
Happens with me too. Interestingly, it happens only with the `debug` key. Other keys don't get overwritten if the `db` is initialized many times in the same app. 

```
db.defaults({ lastId: -1, lastTimestamp: 0, favorites: [], debug: 0 }).write();
```

--- UPDATE

I have a feeling this appears because I am using many instances of the same DB. So if an instance that was initialized before is `written`, it overrides the changes done by the new instance because the DB is stored in memory with the instance.

**Closed** 2021-05-21 07:38 UTC
