### ISSUE TITLE
[Question] One file per entry

### ISSUE THREAD

**Issue by ehhc** [typicode/lowdb#358] opened 2019-08-04 16:28 UTC
Hi, 
is it possible to write one file per database entry?
For example if my database holds the following objects [{note1}, {note2}], etc. i would like to get two files (note1.json, note2.json).

is that possible? 
Thanks :)

**Comment by TokenChingy** [comment] 2019-08-05 10:54
Not in an easy way. Question though, why would you?

**Comment by ehhc** [comment] 2019-08-10 16:14
@TokenChingy Thanks for your answer. I want it for the following reason: I'm developing a note taking app and i would like to use lowdb to store the notes (due to the nice find and filter possibilites.. :) ), but i also want each note to be stored in a separate (markdown) file so that they also can be accessed by other programms..

Anyway, i understand that that's out of the scope of the current lowdb (and it's adapters). However, i wrote a custom adapter (https://github.com/ehhc/lowdbMultifileAdapter) i hope to do what i want. 
Would you (or other constributors) do me a favor and have a look at the code? I'm still new to nodejs developement and maybe i did something obvious wrong..

**Comment by ehhc** [comment] 2019-08-10 16:15
Or maybe @typicode can have a look on it? :)

**Comment by TokenChingy** [comment] 2019-08-12 02:10
@ehhc I'll have a look at it this week.

**Comment by typicode** [comment] 2021-05-21 07:19
Closing as the issue is pretty old. That said, creating a custom adapter was the right approach :+1:

**Closed by typicode** 2021-05-21 07:19 UTC
